project:
  host: "0.0.0.0"
  port: 8080
mysql:
  username: "root"
  password: "wjlroot"
  db_host: "127.0.0.1"
  db_port: 3306
  db_name: "framework"
  charset: "utf8"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: 500